language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
after_success: ./deploy-gh.sh
env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="dist"
    - TARGET_BRANCH="gh-pages"
    - SSH_KEY="kazoo_rsa"
    - GIT_NAME="travis"
    - GIT_EMAIL="build@travis-ci.org"
before_install:
- openssl aes-256-cbc -K $encrypted_7d63babd5212_key -iv $encrypted_7d63babd5212_iv -in kazoo_rsa.enc -out kazoo_rsa -d
